# Generated by Django 4.2.6 on 2024-04-01 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Instytucja', 'verbose_name_plural': 'Instytucje'},
        ),
    ]
