# Generated by Django 4.2.6 on 2024-04-01 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0002_alter_institution_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
