# Generated by Django 4.2.6 on 2024-04-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0003_donation_donation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='bags',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
